{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: acpype
  version: {{ version }}

source:
  git_rev: "recipe"
  git_url: https://github.com/alanwilter/acpype.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openbabel
    - ambertools

test:
  commands:
    - acpype -v

about:
  home: https://alanwilter.github.io/acpype/
  license: GPL-3.0-or-later
  license_file: LICENSE
