H    1   0.30
D    1   0.30
C    6   0.85
N    7   0.78
O    8   0.85
F    9   0.53
P   15   1.08  //original 1.20 from midas parameter
S   16   1.04
Cl  17   0.92
Br  35   1.09
I   53   1.50
Si  14   1.11  //empirical (0)
Be   4   0.56  //empirical (+2)
B    5   0.81  //parameter // 12-8-2018 old value is 0.39 for (+3)
//newly added nonmetallic elements on 12-8-2018
He   2   0.32
Ne  10   0.69
Ar  18   0.97
Kr  36   1.10
Te  52   1.35
Xe  54   1.30
Na  11   0.97
Mg  12   0.66
K   19   1.33
Ca  20   0.99
Mn  25   0.80
Fe  26   0.74
Cu  29   0.96
Zn  30   0.74
// for nonmetallic elements added on 12-8-2018: empirical formula is r * 1.090478 -0.088962, r2=0.9114
Al  13   0.64  //empirical (+3)
Li   3   0.85  //empirical (+1)
Sc  21   0.84  //empirical (+3)
Ti  22   0.77  //empirical (+3)
V   23   0.74  //empirical (+3)
Cr  24   0.72  //empirical (+3)
Co  27   0.79  //empirical (+2)
Ni  28   0.79  //empirical (+2)
Ga  31   0.72  //empirical (+3)
Ge  32   0.82  //empirical (+2)
As  33   1.13  //empirical (0)
Se  34   1.12  //empirical (0)
Sr  38   1.25  //empirical (+2)
Ba  56   1.41  //empirical (+2)
Ru  44   0.78  //empirical (+3)
Rh  45   0.76  //empirical (+3)
Pd  46   0.95  //empirical (+2)
Ag  47   1.02  //empirical (+1)
Cd  48   1.03  //empirical (+2)
Pt  78   0.89  //empirical (+2)
Au  79   1.42  //empirical (+1)
Hg  80   1.26  //empirical (+2)
Tl  81   1.55  //empirical (+1)
Pb  82   1.26  //empirical (+2)
//for old parameters:  empircal formula: parameter = 0.9396*r + 0.006 where r is the atomic radius at specific valence state
Rb  37   2.11
Y   39   1.62
Zr  40   1.48
Nb  41   1.37
Mo  42   1.45
Tc  43   1.56
In  49   1.44
Sn  50   1.41
Sb  51   1.38
Cs  55   2.25
La  57   1.69
Lu  71   1.60
Hf  72   1.50
Ta  73   1.38
W   74   1.46
Re  75   1.59
Os  76   1.28
Ir  77   1.37
Bi  83   1.46
Rn  86   1.45
// for metallic elements added on 12-8-2018: empirical formula is r * 0.754974 -0.182217, r2=0.8566 
