# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcpypeJob',
            fields=[
                ('juser', models.CharField(max_length=30)),
                ('jname', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('jdate', models.CharField(max_length=30)),
                ('jobdir', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jstatus', models.CharField(max_length=20)),
                ('jpid', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('juser', '-jobdir'),
                'abstract': False,
            },
        ),
    ]
