H    1   0.30
D    1   0.30
C    6   0.85
N    7   0.78
O    8   0.85
F    9   0.53
Na  11   0.97
Mg  12   0.66
P   15   1.08     //original 1.20 from midas parameter
S   16   1.04
Cl  17   0.92
K   19   1.33
Ca  20   0.99
Fe  26   0.74
Mn  28   0.80
Cu  29   0.96
Zn  30   0.74
Br  35   1.09
I   53   1.50
Si  14   1.11  //empirical (0)
AL  27   0.64  //empirical (+3)
Li   3   0.85  //empirical (+1)
Be   4   0.56  //empirical (+2)
B    5   0.39  //empirical (+3)
Sc  21   0.84  //empirical (+3)
Ti  22   0.77  //empirical (+3)
V   23   0.74  //empirical (+3)
Cr  24   0.72  //empirical (+3)
Co  27   0.79  //empirical (+2)
Ni  28   0.79  //empirical (+2)
Ga  31   0.72  //empirical (+3)
Ge  32   0.82  //empirical (+2)
As  33   1.13  //empirical (0)
Se  34   1.12  //empirical (0)
Sr  38   1.25  //empirical (+2)
Ba  56   1.41  //empirical (+2)
Ru  44   0.78  //empirical (+3)
Rh  45   0.76  //empirical (+3)
Pd  46   0.95  //empirical (+2)
Ag  47   1.02  //empirical (+1)
Cd  48   1.03  //empirical (+2)
Pt  78   0.89  //empirical (+2)
Au  79   1.42  //empirical (+1)
Hg  80   1.26  //empirical (+2)
Tl  81   1.55  //empirical (+1)
Pb  82   1.26  //empirical (+2)
// empirical formula: parameter = 0.9396*r + 0.006 
// r is the atomic radius at specific valence state
