# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_file', models.FileField(null=True, upload_to='')),
                ('charge_method', models.CharField(choices=[('bcc', 'bcc (default)'), ('gasteiger', 'gasteiger'), ('user', 'user')], default='bcc', max_length=20)),
                ('net_charge', models.IntegerField(default=0, null=True)),
                ('multiplicity', models.PositiveIntegerField(default=1, null=True)),
                ('atom_type', models.CharField(choices=[('gaff', 'GAFF (default)'), ('amber', 'AMBER')], default='gaff', max_length=20)),
                ('juser', models.CharField(max_length=30)),
                ('jstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('jcelery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jzipped', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
