# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_method', models.CharField(choices=[(1, 'bcc (default)'), (2, 'gasteiger'), (5, 'user')], default=1, max_length=20)),
                ('net_charge', models.IntegerField(default=1)),
                ('multiplicity', models.IntegerField(default=1)),
                ('atom_type', models.CharField(choices=[(1, 'GAFF (default)'), (2, 'AMBER')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='home/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
